spring.application.name=SocialHub

spring.datasource.url=jdbc:mysql://localhost:3306/socialhub
spring.datasource.username=socialhub_user
spring.datasource.password=Srijan4455@t

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=change-this-to-a-long-secret-key-change-this-to-a-long-secret
app.jwt.expMinutes=60
app.frontend.url=http://localhost:3000