spring.application.name=SocialHub

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://caboose.proxy.rlwy.net:56573/railway
spring.datasource.username=postgres
spring.datasource.password=viYFvzGzWhPQDfTEqvAhlzNvAeueQMUC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

app.jwt.secret=SocialHubSecretKeyForJwtTokenGeneration123456789
app.jwt.expMinutes=1440